// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace HBD.EntityFramework.TestDal
{
    using HBD.EntityFramework.Core;

    // ParentChildren
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class ParentChildrenConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ParentChildren>
    {
        public ParentChildrenConfiguration()
            : this("dbo")
        {
        }

        public ParentChildrenConfiguration(string schema)
        {
            ToTable("ParentChildren", schema);
            HasKey(x => new { x.ParentId, x.ChildrenId });

            Property(x => x.ParentId).HasColumnName(@"ParentId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.ChildrenId).HasColumnName(@"ChildrenId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("nvarchar").IsRequired().HasMaxLength(100);
            Property(x => x.CreatedOn).HasColumnName(@"CreatedOn").HasColumnType("datetime").IsRequired();
            Property(x => x.UpdatedBy).HasColumnName(@"UpdatedBy").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.UpdatedOn).HasColumnName(@"UpdatedOn").HasColumnType("datetime").IsOptional();
            Property(x => x.RowVersion).HasColumnName(@"RowVersion").HasColumnType("timestamp").IsOptional().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Computed);

            // Foreign keys
            HasRequired(a => a.Child).WithMany(b => b.ParentChildrens).HasForeignKey(c => c.ChildrenId).WillCascadeOnDelete(false); // FK_ParentChildrent_Childrent
            HasRequired(a => a.Parent).WithMany(b => b.ParentChildrens).HasForeignKey(c => c.ParentId).WillCascadeOnDelete(false); // FK_ParentChildrent_Parent
        }
    }

}
// </auto-generated>
